Completely refactor cowbull-control control plane script

diff --git a/cowbull-control b/cowbull-control
--- a/cowbull-control
+++ b/cowbull-control
@@ -2,42 +2,71 @@
 #
 # 1. Load source modules
 #
-source scripts/v3/setDefaults.sh
-source scripts/v3/setVendorSpecifics.sh
-source scripts/v3/dependencyCheck.sh
-source scripts/v3/showError.sh
-source scripts/v3/showWelcome.sh
-source scripts/v3/deployServices.sh
-source scripts/v3/deployAzureSpecific.sh
-source scripts/v3/deployIngress.sh
-source scripts/v3/deployWebappService.sh
-source scripts/v3/processArgument.sh
-source scripts/v3/parseArgs.sh
 
-source scripts/v2/showHelp.sh
-source scripts/v2/showInfo.sh
-source scripts/v2/removeK8SComponents.sh
-source scripts/v2/deployK8SComponents.sh
-source scripts/v2/showConfig.sh
-source scripts/v2/showTeardown.sh
-source scripts/v2/showSpinup.sh
-source scripts/v2/processContinue.sh
-source scripts/v2/getContext.sh
+# function to validate core2 dependencies and pre-reqs.
+source scripts/dependencyCheck.sh
+
+# function to deploy Kubernetes configurations, dep., svc., etc.
+source scripts/deployK8SComponents.sh
+
+# function to get context for kubectl
+source scripts/getContext.sh
+
+# function to parse arguments
+source scripts/parseArgs.sh
+
+# function to process each argument
+source scripts/processArgument.sh
+
+# function to ask user if they want to continue
+source scripts/processContinue.sh
+
+# function to remove Kubernetes configurations
+source scripts/removeK8SComponents.sh
+
+# function to set default values for variables
+source scripts/setDefaults.sh
+
+# function to define the imperative commands needed to apply
+# or delete kubernets objects.
+source scripts/setImperatives.sh
+
+# function to set vendor specific information (e.g. paths, etc.)
+source scripts/setVendorSpecifics.sh
+
+# function to show the configuration that will be deployed
+source scripts/showConfig.sh
+
+# function to handle errors
+source scripts/showError.sh
+
+# function to show help
+source scripts/showHelp.sh
+
+# function to show additional usage information
+source scripts/showInfo.sh
+
+# function to show welcome message
+source scripts/showWelcome.sh
+
 
 #
 # 2. Show welcome message
 #
 showWelcome
 
+
 #
 # 3. Set defaults and initialize variables
 #
 setDefaults
 
+
 #
 # 4. Parse command line arguments
 #
 parseArgs
+
 
 #
 # 5. Process each argument, validate it, and act on it.
@@ -48,18 +77,21 @@ while true; do
     shift $SHIFT_AMOUNT
 done
 
+
 #
 # 6. Check dependencies
 #
 dependencyCheck
+
 
 #
 # 7. Compute specific variable for each vendor
 #
 setVendorSpecifics
 
+
 #
-# 7. Show the welcome message. Differs based on tear down or instantiate
+# 8. Show the welcome message. Differs based on tear down or instantiate
 #    actions.
 #
 echo "|------------------------------------------------------------------|" >&2
@@ -77,36 +109,89 @@ fi
 echo "|                                                                  |" >&2
 echo "|------------------------------------------------------------------|" >&2
 
+
 #
-# 9. Output the configuration to the user
+# 9. Validate vendor prereqs
+#
+echo >&2
+echo "Validating environment and prerequisites" >&2
+echo "----------------------------------------" >&2
+echo >&2
+. $VENDOR_PATH/validate.sh
+return_status=$?
+if (( $return_status != 0 ))
+then
+    showError "Error" 7 "Vendor validation for prerequisites failed."
+
+    processContinue
+    if (( $? != 1 )); then echo >&2; exit 0; fi
+
+    # User accepted to continue, so set quiet so that they are not
+    # prompted twice.
+    QUIET=1
+fi
+
+
+#
+# 10. Output the configuration to the user
 #
 showConfig
 
+
 #
-# 10. If not in quiet mode, confirm the action with the user because it
+# 11. Set the imperative commands based on args
+#
+setImperatives
+
+
+#
+# 12. If not in quiet mode, confirm the action with the user because it
 #    is dangerous and not revertable.
 #
+
+# Check quiet is defined, if it's not, set it to no
 if [[ $QUIET"X" == "X" ]]; then QUIET=0; fi
+
 if (( $QUIET != 1 ))
 then
     processContinue
     if (( $? != 1 )); then echo >&2; exit 0; fi
 fi
 
-#
 
 #
-# 12. Check if tear down or instantiate
+# 13. Check if tear down or instantiate cluster
 #
-if (( $TEARDOWN == 1 ))
+if (( $DEPLOYCLUSTER == 1 )) || (( $DEPLOYFULL == 1 ))
 then
-    . $VENDOR_PATH/spindown-cluster
-else
-    . $VENDOR_PATH/spinup-cluster
+    if (( $TEARDOWN == 1 ))
+    then
+        removeK8Scomponents
+        . $VENDOR_PATH/teardown
+    else
+        . $VENDOR_PATH/spinup
+    fi
 fi
 
+
 #
-# 13. Done.
+# 14. teardown or deploy the services
+#
+if (( $DEPLOYSERVICES == 1 )) || (( $DEPLOYFULL == 1 ))
+then
+    if (( $TEARDOWN == 1 ))
+    then
+        #
+        # Check if deploy full has been set (the default); if it
+        # is, then don't do anything else as the services are
+        # always pulled down before the cluster.
+        #
+        if (( $DEPLOYFULL != 1 )); then removeK8Scomponents; fi
+    else
+        deployK8Scomponents
+    fi
+fi
+
 #
 echo
 echo "Done."
